jena:
  type: fuseki
  dropExistModel: false
  modelName: biluProdFusion
  fusekiURI: http://miami-fuseki:3330/knowledge

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://miami-springcloud-eureka:8861/eureka/