jena:
  type: fuseki
  dropExistModel: false
  modelName: biluDevFusion
  fusekiURI: http://localhost:3330/knowledge

spring:
  data:
    mongodb:
      uri: mongodb://tahiti:Qs7UDDUliY@47.104.8.27:27101/zhinengtiaojie

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8861/eureka/

miami:
  mongocase:
    database: zhinengtiaojie
    collection:
      case: aj_basic